### ISSUE TITLE
UCIE maps to narrow LAB spectrum microbiome data

### ISSUE THREAD

**Issue by savvas-paragkamian** [mikelkou/ucie#1]
U-CIE is a great tool, so simple idea and robust implementation! 

I am trying to apply U-CIE to my soil microbiome data (amplicon - 16s rRNA), especially the sample sites. After the UMAP of the community matrix (SITES X GENERA) I supplied the 3d UMAP data to the tool (attached file). 

My problem is that the projection of U-CIE to colors is narrow, mostly around green. 
I tried to toggle the parameters (both in UI and in R package) but I fail to expand the color coverage.
 
<img width="1512" alt="Screenshot 2023-10-13 at 2 45 20 PM" src="https://github.com/mikelkou/ucie/assets/9021276/6bf4da6a-1565-4221-870a-362e9fa75c48">

Is there a way, to cover a bigger part of the color space?

[umap_samples_3.txt](https://github.com/mikelkou/ucie/files/12893170/umap_samples_3.txt)

**Comment by savvas-paragkamian** [comment]
I tried with different dimension reduction methods like PCoA and nMDS and the U-CIE worked super. 
I wonder though why this is the case for the UMAP data. 
It is an error of my implementation of UMAP? 
Or maybe has something to do with the nature of data?

<img width="1488" alt="Screenshot 2023-10-14 at 2 52 06 AM" src="https://github.com/mikelkou/ucie/assets/9021276/8baefc6a-ffaf-4e82-9114-e8d06a80db15">

[ordination_pcoa_for_ui.txt](https://github.com/mikelkou/ucie/files/12900599/ordination_pcoa_for_ui.txt)

**Comment by mikelkou** [comment]
Thank you so much for your nice words and the effort to make good use of it. I doubt that there was an error of your implementation of the UMAP algorithm. I tend to believe that UMAP's distribution is not centered, making the optimization algorithm not doing a a great job. I can have a look into it and if centering the data helps but feel free to do a PR if you have a nice implementation that works as well.

Happy to see that you got nice results! :D
